import React from "react";
import { UserDetails } from "./UserDetails";
const userList = [
  { id: 1, subject: "hello", body: "hi", view_count: 1 },
  { id: 2, subject: "hello", body: "hi", view_count: 2 },
  { id: 3, subject: "hello", body: "hi", view_count: 3 },
  { id: 4, subject: "hello", body: "hi", view_count: 4 },
  { id: 5, subject: "hello", body: "hi", view_count: 5 },
  { id: 6, subject: "hello", body: "hi", view_count: 6 },
  { id: 7, subject: "hello", body: "hi", view_count: 7 },
  { id: 8, subject: "hello", body: "hi", view_count: 8 },
  { id: 9, subject: "hello", body: "hi", view_count: 9 },
  { id: 10, subject: "hello", body: "hi", view_count: 10 },
  { id: 11, subject: "hello", body: "hi", view_count: 11 },
  { id: 12, subject: "hello", body: "hi", view_count: 12 },
  { id: 13, subject: "hello", body: "hi", view_count: 13 },
  { id: 14, subject: "hello", body: "hi", view_count: 14 },
  { id: 15, subject: "hello", body: "hi", view_count: 15 },
  { id: 16, subject: "hello", body: "hi", view_count: 16 },
  { id: 17, subject: "hello", body: "hi", view_count: 17 },
  { id: 18, subject: "hello", body: "hi", view_count: 18 },
  { id: 19, subject: "hello", body: "hi", view_count: 19 },
  { id: 20, subject: "hello", body: "hi", view_count: 20 },
  { id: 21, subject: "hello", body: "hi", view_count: 21 },
  { id: 22, subject: "hello", body: "hi", view_count: 22 },
  { id: 23, subject: "hello", body: "hi", view_count: 23 },
  { id: 24, subject: "hello", body: "hi", view_count: 24 },
  { id: 25, subject: "hello", body: "hi", view_count: 25 },
  { id: 26, subject: "hello", body: "hi", view_count: 26 },
  { id: 27, subject: "hello", body: "hi", view_count: 27 },
  { id: 28, subject: "hello", body: "hi", view_count: 28 },
  { id: 29, subject: "hello", body: "hi", view_count: 29 },
  { id: 30, subject: "hello", body: "hi", view_count: 30 },
  { id: 31, subject: "hello", body: "hi", view_count: 31 },
  { id: 32, subject: "hello", body: "hi", view_count: 32 },
  { id: 33, subject: "hello", body: "hi", view_count: 33 },
  { id: 34, subject: "hello", body: "hi", view_count: 34 },
  { id: 35, subject: "hello", body: "hi", view_count: 35 },
  { id: 36, subject: "hello", body: "hi", view_count: 36 },
  { id: 37, subject: "hello", body: "hi", view_count: 37 },
  { id: 38, subject: "hello", body: "hi", view_count: 38 },
  { id: 39, subject: "hello", body: "hi", view_count: 39 },
  { id: 30, subject: "hello", body: "hi", view_count: 40 },
  { id: 41, subject: "hello", body: "hi", view_count: 41 },
  { id: 42, subject: "hello", body: "hi", view_count: 42 },
  { id: 43, subject: "hello", body: "hi", view_count: 43 },
  { id: 44, subject: "hello", body: "hi", view_count: 44 },
  { id: 45, subject: "hello", body: "hi", view_count: 45 },
  { id: 46, subject: "hello", body: "hi", view_count: 46 },
  { id: 47, subject: "hello", body: "hi", view_count: 47 },
  { id: 48, subject: "hello", body: "hi", view_count: 48 },
  { id: 49, subject: "hello", body: "hi", view_count: 49 },
  { id: 50, subject: "hello", body: "hi", view_count: 50 },
  { id: 51, subject: "hello", body: "hi", view_count: 51 },
  { id: 52, subject: "hello", body: "hi", view_count: 52 },
  { id: 53, subject: "hello", body: "hi", view_count: 53 },
  { id: 54, subject: "hello", body: "hi", view_count: 54 },
  { id: 55, subject: "hello", body: "hi", view_count: 55 },
  { id: 56, subject: "hello", body: "hi", view_count: 56 },
  { id: 57, subject: "hello", body: "hi", view_count: 57 },
  { id: 58, subject: "hello", body: "hi", view_count: 58 },
  { id: 59, subject: "hello", body: "hi", view_count: 59 },
  { id: 60, subject: "hello", body: "hi", view_count: 60 },
  { id: 61, subject: "hello", body: "hi", view_count: 61 },
  { id: 62, subject: "hello", body: "hi", view_count: 62 },
  { id: 63, subject: "hello", body: "hi", view_count: 63 },
  { id: 64, subject: "hello", body: "hi", view_count: 64 },
  { id: 65, subject: "hello", body: "hi", view_count: 65 },
  { id: 66, subject: "hello", body: "hi", view_count: 66 },
  { id: 67, subject: "hello", body: "hi", view_count: 67 },
  { id: 68, subject: "hello", body: "hi", view_count: 68 },
  { id: 69, subject: "hello", body: "hi", view_count: 69 },
  { id: 70, subject: "hello", body: "hi", view_count: 70 },
  { id: 71, subject: "hello", body: "hi", view_count: 71 },
  { id: 72, subject: "hello", body: "hi", view_count: 72 },
  { id: 73, subject: "hello", body: "hi", view_count: 73 },
  { id: 74, subject: "hello", body: "hi", view_count: 74 },
  { id: 75, subject: "hello", body: "hi", view_count: 75 },
  { id: 76, subject: "hello", body: "hi", view_count: 76 },
  { id: 77, subject: "hello", body: "hi", view_count: 77 },
  { id: 78, subject: "hello", body: "hi", view_count: 78 },
  { id: 79, subject: "hello", body: "hi", view_count: 79 },
  { id: 80, subject: "hello", body: "hi", view_count: 80 },
  { id: 81, subject: "hello", body: "hi", view_count: 81 },
  { id: 82, subject: "hello", body: "hi", view_count: 82 },
  { id: 83, subject: "hello", body: "hi", view_count: 83 },
  { id: 84, subject: "hello", body: "hi", view_count: 84 },
  { id: 85, subject: "hello", body: "hi", view_count: 85 },
  { id: 86, subject: "hello", body: "hi", view_count: 86 },
  { id: 87, subject: "hello", body: "hi", view_count: 87 },
  { id: 88, subject: "hello", body: "hi", view_count: 88 },
  { id: 89, subject: "hello", body: "hi", view_count: 89 },
  { id: 90, subject: "hello", body: "hi", view_count: 90 },
  { id: 91, subject: "hello", body: "hi", view_count: 91 },
  { id: 92, subject: "hello", body: "hi", view_count: 92 },
  { id: 93, subject: "hello", body: "hi", view_count: 93 },
  { id: 94, subject: "hello", body: "hi", view_count: 94 },
  { id: 95, subject: "hello", body: "hi", view_count: 95 },
  { id: 96, subject: "hello", body: "hi", view_count: 96 },
  { id: 97, subject: "hello", body: "hi", view_count: 97 },
  { id: 98, subject: "hello", body: "hi", view_count: 98 },
  { id: 99, subject: "hello", body: "hi", view_count: 99 },
  { id: 100, subject: "hello", body: "hi", view_count: 100 },
];
export const Users = () => {
  return (
    <div>
      <ol className='ul'>
        {userList.map((user) => (
          <UserDetails key={user.id} details={user} />
        ))}
      </ol>
    </div>
  );
};
